# 1. 管道运行设置
pipeline_settings:
  force_reprocess: false
  batch_size: 32

# 2. 编码器设置
encoder_settings:
  encoder_type: "intern_vl"
  model_name: "OpenGVLab/InternVL3-1B-hf"
  device: "cuda:0"
  target_dimensions:
    multimodal: 768

# 3. 数据集处理设置
dataset_settings:
  # dataset_root_path: "/home/ai/ylzuo/UniMAG/hugging_face"
  datasets_to_process:
    - "Grocery"
  modalities_to_process:
    - "multimodal"