# 1. 管道运行设置
pipeline_settings:
  force_reprocess: true    # 是否强制重新处理已存在的特征文件
  batch_size: 128             # 编码时使用的批处理大小 (1B模型可以适当调大)

# 2. 编码器设置
encoder_settings:
  # 编码器类型，用于工厂创建正确的编码器实例
  # 对应 @EncoderFactory.register("intern_vl")
  encoder_type: "intern_vl"
  
  # 使用的编码器模型 (Hugging Face 模型名称)
  model_name: "OpenGVLab/InternVL3-1B-hf"
  
  # 缓存目录 (可选, 留空则使用Hugging Face默认缓存)
  # cache_dir: "/path/to/your/cache"
  
  # 运行设备 (可选, 留空则自动检测 "cuda" 或 "cpu")
  device: "cuda:1"
  
  # 目标维度 (可选, 如果不指定或为null, 则使用模型的原生维度)
  # InternVL3-1B 的原生文本维度是 896
  target_dimensions:
    text: 768
    image: 768
    multimodal: 768

# 3. 数据集处理设置
dataset_settings:
  # 数据集根路径 (可选, 留空则使用服务器的默认路径 /home/ai/MMAG)
  dataset_root_path: "/home/ai/ylzuo/UniMAG/hugging_face"
  
  # 要处理的数据集列表 (可选, 留空或省略则处理hugging_face/下的所有数据集)
  datasets_to_process:
    - "books-nc-50"
  
  # 要为这些数据集处理的模态列表
  modalities_to_process:
    - "text"
    - "image"
    - "multimodal"