name: Movies
graph_path: /home/ai/lys/MAG/MAGB-master/dataset/books-nc/books-ncGraph.pt
v_emb_path: /home/ai/lys/MAG/MAGB-master/dataset/books-nc/t5vit_feat.pt
t_emb_path: /home/ai/lys/MAG/MAGB-master/dataset/books-nc/t5vit_feat.pt
train_ratio: 0.6
val_ratio: 0.2
lp_val_ratio: 0.01
lp_test_ratio: 0.08
edge_split_path: None
num_neg: 1000