name: Movies
graph_path: /home/ai/MMAG/Movies/MoviesGraph.pt 
v_emb_path: /home/ai/lys/MAG/MAGB-master/dataset/Movies/ImageFeature/Movies_openai_clip-vit-large-patch14.npy
#v_emb_path: /home/ai/lys/MAG/MAGB-master/dataset/Movies/ImageFeature/Movies_Qwen2-VL-7B-Instruct_visual.npy
t_emb_path: /home/ai/lys/MAG/MAGB-master/dataset/Movies/TextFeature/Movies_Qwen2_VL_7B_Instruct_512_mean.npy
#v_emb_path: /home/ai/MMAG/Movies/image_features/Movies_image_Qwen_Qwen2_5_VL_3B_Instruct_768d.npy
#t_emb_path: /home/ai/MMAG/Movies/text_features/Movies_text_Qwen_Qwen2_5_VL_3B_Instruct_native.npy
train_ratio: 0.6
val_ratio: 0.2
lp_val_ratio: 0.2
lp_test_ratio: 0.2
edge_split_path: None
num_neg: 5000