name: lp
n_epochs: 10
lr: 0.001
fewshots: False
weight_decay: 1e-5
n_runs: 3
batch_size: 2048

predictor_hidden: 128
predictor_out: 1
predictor_layers: 2
predictor_dropout: 0.5

self_loop: False
undirected: False