# QE (Quality Evaluation) 任务配置文件示例
# 任务: 在 Grocery 数据集上，使用 GCN 模型，评估模态匹配性能

# 任务定义
task:
  name: modality_matching

# 数据集配置
dataset:
  name: Grocery
  data_root: /home/ai/MMAG

# 使用的嵌入向量的配置
embedding:
  encoder_name: "Qwen/Qwen2.5-VL-3B-Instruct"
  dimension: 768

# GNN 模型配置
model:
  name: GCN
  # GCN模型的参数，in_dim 将由 trainer.py 动态计算
  params:
    hidden_dim: 256
    num_layers: 2
    dropout: 0.5

# 训练配置
training:
  epochs: 50
  lr: 0.001
