# QE (Quality Evaluation) 任务配置文件示例
# 任务: 在 Grocery 数据集上，使用 GCN 模型，评估模态检索性能

# 任务定义
task:
  name: modality_retrieval

# 数据集配置
dataset:
  name: Grocery
  data_root: /home/ai/MMAG

# 使用的嵌入向量的配置
embedding:
  encoder_name: "Qwen/Qwen2.5-VL-3B-Instruct"
  dimension: 768

# GNN 模型配置
model:
  name: GCN
  params:
    hidden_dim: 256
    num_layers: 2
    dropout: 0.5

# 训练配置
training:
  epochs: 50
  lr: 0.001
  patience: 10
  val_ratio: 0.1
  tau: 0.07

# 评估配置
evaluation:
  top_k: [1, 5, 10, 20]